### PR TITLE
#76 stopped creating a separate folder when exporting

### PR DESCRIPTION
**Pull request by evolverine**
#76

### CODE REVIEW

**Comment by Stvad** [comment]
I'm pretty sure this breaks snapshot functionality :)

**Comment by evolverine** [comment]
I've now made it a setting.

**Comment by Stvad** [comment]
Overall looks good to me, just one thing `create_directory` does not clearly reveal intention. I.e. it's not clear if it means "create directory I point at if it does not exist" vs "create a subdirectory for deck". So I'd suggest you naming it something like`create_subdir_for_deck` or `create_deck_subdirectory`

**Comment by evolverine** [comment]
👍 I shall do it this weekend, probably.

**Comment by evolverine** [comment]
ok, did it today 🙂️

**Comment by Stvad** [comment]
Nice, thank you! :)

**Comment by Stvad** [comment]
@evolverine Hey! I believe you haven't included changes to `ui_files/config.ui` here as when I re-generate UI config dialog - your changes are missing. Would appreciate if you can create a PR for those!

**Comment by evolverine** [comment]
Oh! Sure, I can take a look later today to see what happened there.

**Comment by evolverine** [comment]
Looks like @ohare93 kindly got to it before me, in #87

**Comment by ohare93** [comment]
Oh I didn't see this was referenced here :sweat_smile: all fixed now :wink:

**Pull request merged**
